export const courses = [
    { "Expired" : false,
      "star" : true,
      "image":"images/imageMask.png",
      "title": "Acceleration",
      "subject":"Physics",
      "grade":" 7",
      "additional": "+2",
      "units":"4",
      "lessons":"18",
      "topics" :"24",
      "dropdownOptions": ["Mr. Frank Class A", "Mr. Frank Class B","Mr. Frank Class C"],
      "students":"50",
      "startdate":"21-Jan-2020",
      "enddate":"21-Aug-2020",
      "iconsEnabled": { 
        "view": true, 
        "calender": true, 
        "favourite": true, 
        "dashboard": true }
      },
    {  "Expired" : false,
      "star" : true,
      "image":"images/imageMask-1.png",
      "title": "Displacement, Velocity and Speed",
      "subject":"Physics 2" ,
      "grade":" 6",
      "additional": "+3",
      "units":"2",
      "lessons":"15",
      "topics" :"20",
      "dropdownOptions": [],
      "students": "",
      "startdate":"",
      "enddate":"",
      "iconsEnabled": { 
        "view": true, 
        "calender": false, 
        "favourite": false, 
        "dashboard": true } },
    { "Expired" : false,
      "star" : true,
      "image":"images/imageMask-3.png",
      "title": "Introduction to Biology: Micro organisms and how they affec...",
      "subject":"Biology",
      "grade":" 4",
      "additional": "+1",
      "units":"5",
      "lessons":"16",
      "topics" :"22",
      "dropdownOptions": ["All Classes", "Mr. Frank Class B","Mr. Frank Class C"],
      "students":"300",
      "startdate":"",
      "enddate":"",
      "iconsEnabled": { 
        "view": true, 
        "calender": false, 
        "favourite": false, 
        "dashboard": true } },
       { 
      "Expired" : true,
      "star" : false,
      "image":"images/imageMask-2.png",
      "title": "Introduction to High School Mathematics",
      "subject":"Mathematics",
      "grade":"8",
      "additional": "+3",
      "units":"",
      "lessons":"",
      "topics" :"",
      "dropdownOptions": ["All Classes", "Mr. Frank Class A","Mr. Frank Class C"],
      "students":"44",
      "startdate":"14-Oct-2019",
      "enddate":"20-Oct-2020",
      "iconsEnabled": { 
        "view": true, 
        "calender": true, 
        "favourite": true, 
        "dashboard": true } }
]

module.exports = courses;